services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springSecurityJwt
    image: spring-security-jwt:latest
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:root@localhost:3306/jwt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
